### ISSUE TITLE
Simpler download instructions

### ISSUE THREAD

**Issue by yschimke** [envoyproxy/envoy-mobile#1189]
Curious about getting started guide

https://envoy-mobile.github.io/docs/envoy-mobile/latest/start/building/building.html#bazel-requirements

But it looks like you are publishing artifacts here https://repo1.maven.org/maven2/io/envoyproxy/envoymobile/envoy/0.3.1.11112020/

The current link appears out of date.

**Comment by rebello95** [comment]
Thanks for calling this out. Opened https://github.com/envoyproxy/envoy-mobile/pull/1190 to resolve.
