### ISSUE TITLE
observability: pluggable log handling

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#120]
Upstream Envoy currently performs writes (i.e., for logs) to directories that are unavailable in sandboxed mobile applications. This should be updated to support piping logs to custom logging output targets on mobile

Note: This logging logic should be compiled out of release builds

#34 is the task for android.

**Comment by jpsim** [comment]
Added in https://github.com/envoyproxy/envoy-mobile/pull/1356
