### ISSUE TITLE
bazel 3.7.0 iOS issues

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#1233]
Updating bazel to 3.7.0 or later creates the following errors in the iOS builds:

```
ERROR: /Users/jnino/src/envoy-mobile/library/swift/src/BUILD:5:23: every rule of type _swift_static_framework implicitly depends upon the target '@bazel_tools//tools/objc:libtool', but this target could not be found because of: no such target '@bazel_tools//tools/objc:libtool': target 'libtool' not declared in package 'tools/objc' (did you mean 'libtool.sh'?) defined by /private/var/tmp/_bazel_jnino/e2e6858b12cc5d95c5e2dcf9dce57ac4/external/bazel_tools/tools/objc/BUILD
ERROR: Analysis of target '//:ios_dist' failed; build aborted: Analysis failed
INFO: Elapsed time: 17.452s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (12 packages loaded, 11 targets configured)
```

I have tested with the 0.18.0 release of rules_swift and the 0.21.2 release of rules_apple.

**Comment by junr03** [comment]
cc @keith

**Comment by keith** [comment]
Is envoy using the toolchain from rules_cc? if so that needs to be updated

**Comment by junr03** [comment]
Upstream Envoy? If I understand the bazel definitions correctly, yes. All the cc_* defs in envoy use cc_* defs loaded from @rules_cc under the hood.

**Comment by keith** [comment]
not just the rules but the toolchain itself, rules_cc has a crosstool checked in that's kinda sorta a copy of the one from bazel

**Comment by keith** [comment]
it required an update at the time https://github.com/bazelbuild/rules_cc/pull/82

**Comment by keith** [comment]
Ah nevermind, this is invalid now https://github.com/envoyproxy/envoy-mobile/blob/9543bd6a84297df02652b84c16f19a4c9b1633c7/bazel/swift_static_framework.bzl#L135

**Comment by keith** [comment]
I removed it from bazel here https://github.com/bazelbuild/bazel/commit/f8b51ffc2a8a953f64657ae4a21c9e1f1793dae2

**Comment by keith** [comment]
Can you test your upgrade branch with this? https://github.com/envoyproxy/envoy-mobile/pull/1234
