### ISSUE TITLE
build: upgrade bazel to be in sync with Envoy

### ISSUE THREAD

**Issue by goaway** [envoyproxy/envoy-mobile#1300]
Envoy is currently on Bazel 3.7.2. Envoy Mobile successfully builds on this version, but, presumably due to a bug in bazel, any build errors in the JVM are suppressed, which impedes development and debugging. We've downgraded temporarily back to 3.6.0, but should upgrade again when Envoy moves to a version of Bazel where this is resolved.

**Comment by goaway** [comment]
https://github.com/bazelbuild/bazel/issues/13215

**Comment by goaway** [comment]
Closed above issue; it looks like this is likely the same thing as the issue raised in bazelbuild/bazel#12959.

**Comment by junr03** [comment]
From the last issue linked it looks like any version >= to 4.0.0 has a fix. Will test.

**Comment by junr03** [comment]
Fixed by #1616
