### ISSUE TITLE
bazel: remove abseil workaround

### ISSUE THREAD

**Issue by rebello95** [envoyproxy/envoy-mobile#136]
We are currently running a specific version of abseil in order to make Android AAR builds work on macOS due to this issue: https://github.com/abseil/abseil-cpp/issues/326.

When this issue is resolved, we should revert the changes introduced in https://github.com/lyft/envoy-mobile/pull/133 and stay up-to-date with upstream Envoy.

**Comment by goaway** [comment]
Updated Abseil to current version in Envoy (with patch) here: https://github.com/lyft/envoy-mobile/pull/138

**Comment by chaubunhtha** [comment]
Open thanks you
