### ISSUE TITLE
Access to the number of bytes received from sockets

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1426]
Cronet API exposes a [field](https://chromium.googlesource.com/chromium/src/+/main/components/cronet/android/api/src/org/chromium/net/UrlResponseInfo.java#108) where the total number of bytes received is exposed.

On each callback, Cronet returns the total number of bytes that has been received from the sockets. Here is the definition:

> Returns a minimum count of bytes received from the network to process this request. This count may ignore certain overheads (for example IP and TCP/UDP framing, SSL handshake and framing, proxy handling). This count is taken prior to decompression (for example GZIP) and includes headers and data from all [redirects](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/cronet_url_request.cc;l=250?q=received_byte_count_from_redirects_). This value may change (even for one [UrlResponseInfo](https://chromium.googlesource.com/chromium/src/+/main/components/cronet/android/api/src/org/chromium/net/UrlResponseInfo.java) instance) as the request progresses until completion, when [UrlRequest.Callback.onSucceeded()](https://chromium.googlesource.com/chromium/src/+/main/components/cronet/android/api/src/org/chromium/net/UrlRequest.java#198) is invoked.

This will likely require extra plumbing with the JNI interface.

**Comment by alyssawilk** [comment]
@RyanTheOptimist can you or @RenjieTang comment on what this looks like for H2?  bytes read from socket is a weird thing to pass for streams, so I wonder if we can just fudge header byes and body bytes from what we pass up

**Comment by RyanTheOptimist** [comment]
From my reading of the code, this is trying to count bytes received "for the response". So if the "socket" is multiplexed (h2 or h3) then data received for stream A will not count towards the byte count of data received for stream B. So doing the "fudging" you mention is probably reasonable.

I believe it is trying to count "bytes on the wire" not "bytes in memory" in that this counts the size of compressed headers not decompressed headers, but I'd have to do more digging to convince myself of that

**Comment by carloseltuerto** [comment]
Here is an extra piece of information: this count includes [the redirects](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/cronet_url_request.cc;l=250?q=received_byte_count_from_redirects_).

**Comment by carloseltuerto** [comment]
Cronet number of bytes received is in reality the number of bytes received **that is just enough** to trigger a callback.

For example, if the response header is 92 bytes, and the response body 100 bytes, then the number of bytes received to be declared when invoking the onHeaders callback is 92. However, in reality, the whole 192 has already been received, most of the time. So, unfortunately, EM returns 192 byte received when invoking the onHeaders callback. However, under duress, the same request might be split into two packets, and then EM will declare 92 bytes received when invoking the onHeaders callback. So here are the problems with that:

- Related Cronet tests will be flaky once enabled. Once in a while EM will declare 92 bytes received, and most of the time it will declare 192. However, if Cronet runs under duress, then the outcome becomes 50/50.
- When cancel is invoked by the onHeaders callback, then the final `envoy_final_stream_intel_` declared when invoking the onCancel callback will also include the response body bytes received, most of the time. Cronet excludes the response body received bytes on Cancel and on Redirection.

I do not know if this discrepancy between EM and Cronet matters - the Cronet tests can always be hacked to avoid those offending byte comparisons.

**Comment by alyssawilk** [comment]
sorry, I'm a bit confused.
right now I don't think E-M communicates the number of bytes on up calls, I thought it only does as part of final intel.  Are you asking that to be moved to stream intel, and contain the wire-bytes-read represending the bytes-sent-up-so-far?

**Comment by alyssawilk** [comment]
ah, Charles clued me in about the linked PR.  commented there.
