### ISSUE TITLE
Under IOS, any Android related test fails when a request is sent

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1447]
When an Android Test involves sending an HTTP request, it will fail systematically with this error on IOS:

`Error: 5-06 15:10:13.767][84547][error][envoy_bug] [external/envoy/source/common/network/apple_dns_impl.cc:327] envoy bug failure: interface_index == 0. Details: unexpected interface_index=4294967295`

See:
https://github.com/envoyproxy/envoy-mobile/pull/1430/checks?check_run_id=2502189263
https://github.com/envoyproxy/envoy-mobile/pull/1446/checks?check_run_id=2519075340

However, those tests pass when running under Linux.

**Comment by junr03** [comment]
@carloseltuerto I figured out the issue. Fixing upstream: https://github.com/envoyproxy/envoy/pull/16369

**Comment by carloseltuerto** [comment]
For the record, this failure only present when using localhost. https://github.com/envoyproxy/envoy/pull/16369 worked: now https://github.com/envoyproxy/envoy-mobile/pull/1430 and https://github.com/envoyproxy/envoy-mobile/pull/1446 tests are passing.
