### ISSUE TITLE
Java layer: expose the status line of an HTTP response

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1543]
A normally constituted HTTP response status line goes like this:

A protocol version, a space, the response status code, another space, a possibly empty reason phrase, a carriage return, and a line feed. Example:

```HTTP/1.1 404 Not Found```

Cronet needs access to this data. As far as I can tell, Envoy Mobile only provides the "response status code", in a form of a response header: header name: ```:status```, header value ```200```. The two other fields must be made available. Example:
```:protocol``` ```HTTP/1.1```
```:status```  ```404```
```:reason``` ```Not Found```

Feel free to pick any form. This could also be a single Envoy Mobile proprietary/internal header, example:
```x-envoy-status-line``` ```HTTP/1.1 404 Not Found```

At the moment, Cronvoy hard codes the protocol, and reconstructs the reason with a terrible [hack](https://github.com/envoyproxy/envoy-mobile/blob/main/library/java/org/chromium/net/impl/CronetUrlRequest.java#L780).

**Comment by alyssawilk** [comment]
Huh, now this is an interesting one.

a quick google search tells me 
" HTTP/2 does not define a way to carry the version or reason phrase that is included in an HTTP/1.1 status line."

If that's true for HTTP/2 I suspect it's true for HTTP/3

Envoy is fundamentally designed for HTTP/2.  For HTTP/1.1 we could optionally capture the reason phrase in some well known x-envoy-http1-reason-phrase header but given that folks are largely using Cronvoy for HTTP/2 and above I wonder if it's actually useful given that most of the time we'd still have to synthesize a fake one, i..e. maybe we should just always synthesize unless someone complains they really care about their original reason phrase.

For protocol you can probably snag it from stream info but I suspect that CroNet lies and always sticks HTTP/1.1 in there, at which point again it'd make sense to synthesize.

cc @mattklein123 @snowp for Envoy, @RyanTheOptimist @DavidSchinazi for cronvoy thoughts.

**Comment by snowp** [comment]
I think synthesizing this would just mean bringing the mapping in https://github.com/envoyproxy/envoy-mobile/blob/main/library/java/org/chromium/net/impl/CronetUrlRequest.java#L780 into Envoy? 

How does cronet handle HTTP/2 in this case?

**Comment by RyanTheOptimist** [comment]
When we say that cronet needs the actual status line, do we know what it wants to do with that information / why it needs the status line? As alyssa says, for HTTP/2 and HTTP/3 there is no reason phrase or http version provided. So I wonder what the consumer of this information is going to do with it?

**Comment by alyssawilk** [comment]
I suspect that since Chrome was HTTP/1.1 first it's just how it exposed the
firstline to the user so they could get status.

**Comment by DavidSchinazi** [comment]
I can't imagine a use for the reason phrase. The spec [recommends ignoring it](https://datatracker.ietf.org/doc/html/rfc7230#section-3.1.2). I would suggest to not plumb this in Envoy at all, and instead have Cronvoy maintain a hard-coded list to fill in the reason phrase based on the status and using the [official registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml).

**Comment by carloseltuerto** [comment]
The public Cronet API explicitly exposes the reason phrase:

https://chromium.googlesource.com/chromium/src/+/main/components/cronet/android/api/src/org/chromium/net/UrlResponseInfo.java#61

And tests are failing if the wrong String is present there. So even if this is now a deprecated String, my guess is it is still preferable to populate it given its visibility. So I will use the [official registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) as suggested - thanks David.

And good news, it turns out that the status line protocol is not used - it is not exposed in the API, and tests won't fail if that value is somehow wrong.
