### ISSUE TITLE
"referer" HTTP header requires special logic.

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1551]
When the HTTP response header contains the "referer" entry, then its value must be made canonical. Examples:

- [```http://example.com``` must become ```http://example.com/```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/android/test/javatests/src/org/chromium/net/CronetUrlRequestTest.java;l=591)

- [If invalid, the response header must be stripped out of the "referer" entry](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/android/test/javatests/src/org/chromium/net/CronetUrlRequestTest.java;l=608).

Note: it is assumed that this is not only applicable to Cronvoy. Reference: https://datatracker.ietf.org/doc/html/rfc7231#section-5.5.2

**Comment by alyssawilk** [comment]
@RyanTheOptimist @DavidSchinazi does Chrome sanitize this?  We could add it to the list of HTTP compliance checks Envoy does.

**Comment by carloseltuerto** [comment]
This Chromium change seems related:

https://chromium-review.googlesource.com/c/chromium/src/+/2879998

And this is being tested in Cronet (under Chromium): https://source.chromium.org/search?q=referer&sq=&ss=chromium%2Fchromium%2Fsrc:components%2Fcronet%2F

**Comment by RyanTheOptimist** [comment]
Yeah it looks like the code in Chrome (which is called from the code @carloseltuerto linked to) calls a GURL method specifically for formatting a URL as a referrer. 

https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request.cc;l=476;drc=c14f6f4b9c44fe479a8d004576b42723b2a5feb6;bpv=1;bpt=1

```
void URLRequest::SetReferrer(const std::string& referrer) {
  DCHECK(!is_pending_);
  GURL referrer_url(referrer);
  if (referrer_url.is_valid()) {
    referrer_ = referrer_url.GetAsReferrer().spec();
  } else {
    referrer_ = referrer;
  }
}
```

**Comment by DavidSchinazi** [comment]
@carloseltuerto why do we need special logic here? I'd expect it to be the application's responsibility to correctly fill in the `Referer` header, not the library's. The fact that Cronet was incorrectly dropping that header seems to be an issue specific to Cronet. In other words: what problem do we need to solve here?

**Comment by carloseltuerto** [comment]
@DavidSchinazi Well, without this, we will have a regression. This is the internal bug : b/174837576, and here is a copy of the description:

```
We have observed that the "Referer" header is not transmitted. This was seen in ExoPlayer in Android, using ExoPlayer's cronet extension.

The "Referer" header does not reach the endpoint, but other custom headers are transmitted. We have tested this with 2 endpoints:

a public HTTPS endpoint, provided by an external user. The endpoint was also redirecting to another HTTPS. Unfortunately, the endpoint is not available at the moment.
a local HTTP server, with no redirects involved.
ExoPlayer is setting the headers here:

https://github.com/donparapidos/ExoPlayer/blob/master/extensions/cronet/src/main/java/com/google/android/exoplayer2/ext/cronet/CronetDataSource.java

When attaching a debugger on ExoPlayer, we see that the custom headers (including "Referer") are included in the UrlRequest (java) object before we start the request.

In case it's useful, when ExoPlayer uses HttpUrlConnection directly, the "Referer" header was transmitted. This was tested on both the public HTTPS endpoint and the local HTTP endpoint.
```

**Comment by DavidSchinazi** [comment]
The regression was a bug in Cronet. Why do you think Envoy Mobile has the same bug?

**Comment by carloseltuerto** [comment]
Well, there is a test for this, and Cronvoy fails it -  a temporary ```@Ignored``` is present at the moment.  

https://github.com/envoyproxy/envoy-mobile/blob/main/test/java/org/chromium/net/CronetUrlRequestTest.java#L555

Note: to ease feature/bug tracking, when there is an ```@Ignored```, I tried as much as possible to add the reference to the corresponding github issue.

**Comment by DavidSchinazi** [comment]
I see, thanks for explaining. Assigning to @RenjieTang who will take care of this.

**Comment by RenjieTang** [comment]
I think https://github.com/envoyproxy/envoy-mobile/blob/main/library/common/http/client.cc#L324 might be the best place to add the sanitization logic.
However, unlike Chrome, Envoy/Envoy-mobile doesn't seem to have a URL class to take care of this easily.
Not sure what the tradition is, but should we implement something similar to Chrome? Or can we import some other libraries?

**Comment by alyssawilk** [comment]
I'd be inclined to think that if it's an RFC error we can do it in envoy
upstream rather than only in envoy mobile.  I'd be inclined to add a
runtime guarded sanitization to mutateRequestHeaders
if Http::Utility::Url isn't enough for sanitisation I think you can put
more URL logic there. Lastly there'd be an update
to docs/root/configuration/http/http_conn_man/header_sanitizing.rst to
clarify Envoy now sanitizes that header.

cc @snowp @mattklein123
