### ISSUE TITLE
Cronvoy: support NetworkQualityRttListener Callback

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1552]
Cronvoy will likely have to support [NetworkQualityRttListener](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/components/cronet/android/api/src/org/chromium/net/NetworkQualityRttListener.java) callback. Those are the supported sources: [NetworkQualityObservationSource](https://source.chromium.org/chromium/chromium/src/+/main:net/nqe/network_quality_observation_source.h)

This is used by YouTube and Google Map (GMM)

**Comment by DavidSchinazi** [comment]
@carloseltuerto this is marked as hidden in the Chromium source because it's a prototype. I'd suggest checking in with YouTube and Search to see whether they currently rely on it before we start implementing something similar.

**Comment by carloseltuerto** [comment]
@DavidSchinazi many features are marked as hidden - to be taken with a grain of salt. Major Google Apps use use that.

**Comment by carloseltuerto** [comment]
@DavidSchinazi Well, for YouTube this is under an ExperimentFlag. AGSA does not use it, however, Google Map does - which is quite understandable in their case.

**Comment by DavidSchinazi** [comment]
The fact that they use it and the fact that they get benefits from it are different. We don't need to support something that was added as an experiment if removing it won't change the user experience.

**Comment by carloseltuerto** [comment]
I can not agree more that Implementing something without a redeeming value is in general counterproductive - each line of code is a liability until its deletion. I am in the unfortunate position where I can't really evaluate the importance of a given Cronet feature. I had the intention to ask the Google Map Team since Friday, but if somehow this is used somewhere else, and relied upon, I can't tell.

**Comment by carloseltuerto** [comment]
This feature is not "required" by the two teams using it at the moment at Google: Google Map and YouTube.

Closing this issue for now - can always be resuscitated later on...
