### ISSUE TITLE
Keep header name capitalization for HTTP1

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1558]
For HTTP1, unfortunately, keeping the original capitalization for the header names can't be avoided.

**Comment by alyssawilk** [comment]
reopened - needs to be applied globally not just to alpn pool :-(

**Comment by alyssawilk** [comment]
ditto on this one - hopefully fixed

**Comment by carloseltuerto** [comment]
Unfortunately,  [PR1710](https://github.com/envoyproxy/envoy-mobile/pull/1710") resuscitated this bug.
