### ISSUE TITLE
Cronvoy: per line request header validation

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1559]
With Envoy Mobile, sending the request headers is done with a single call where the they are passed as an array.

[```int sendHeaders(long stream, byte[][] headers, boolean endStream)```](
https://github.com/envoyproxy/envoy-mobile/blob/main/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java#L67)

If any of these request header are syntactically invalid, it is presumed that this call will fail (the returned value won't be zero).

With Cronet, that validation is performed individually - each request header line gets validated through a [JNI call](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/android/java/src/org/chromium/net/impl/CronetUrlRequest.java;l=235):
```
   if (!CronetUrlRequestJni.get().addRequestHeader(mUrlRequestAdapter,
                CronetUrlRequest.this, header.getKey(), header.getValue())) {
       throw new IllegalArgumentException("Invalid header " + header.getKey() + "=" + header.getValue());
   }
```
Furthermore, that's the way to add a request header line, not just validating it.

In order to be on par with this behavior, Envoy Mobile should offer a similar API. Note: returning a String with an error message to be scrapped should be the last resort option.

**Comment by carloseltuerto** [comment]
This is how Cronet validates a request header entry: https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_util.cc;l=341

**Comment by carloseltuerto** [comment]
That validation logic seems rather trivial and unlikely to change soon - maybe it is fine to keep that "line by line" validation in Java. As far as I can tell, it does the same validation as the C++ implementation.

**Comment by DavidSchinazi** [comment]
@carloseltuerto given that all this does is make sure that the header field name is a valid HTTP token (and the definition of those dates back decades), I'd suggest implementing it inside Cronvoy.

**Comment by carloseltuerto** [comment]
@DavidSchinazi fine with me - thanks.
