### ISSUE TITLE
Cronvoy: check if sending clear text is permitted

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1572]
With [Marshmallow (V6.0 / API level 23)](https://source.android.com/setup/start/build-numbers#platform-code-names-versions-api-levels-and-ndk-releases), Android library exposes two system methods indicating if sending a request in clear text (without TLS) is acceptable:

- [public boolean isCleartextTrafficPermitted()](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/security/NetworkSecurityPolicy.java#49)
- [public boolean isCleartextTrafficPermitted(String hostname)](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/security/NetworkSecurityPolicy.java#73)

Cronet seems to [honor](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/cronet_url_request_context.cc;l=357) this policy systematically for Android M+.

And this is how this is [implemented](https://source.chromium.org/chromium/chromium/src/+/main:net/android/java/src/org/chromium/net/AndroidNetworkLibrary.java;l=368) in Java, and how the [C++ calls it](https://source.chromium.org/chromium/chromium/src/+/main:net/url_request/url_request_http_job.cc;l=214).

The cheap solution here is to implement this within the Cronvoy shim, but I suspect that when Envoy Mobile will be used directly on Android (without the Cronvoy shim), then it should also respect this policy.

**Comment by alyssawilk** [comment]
@goaway @junr03 thoughts on this one?
