### ISSUE TITLE
Cronvoy: support Auth Tokens for HTTP Negotiated Authentication, with Kerberos

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1573]
At first sight, Cronet seems to support Auth token generation based on Kerberos crypto library:

[```use_kerberos = !is_ios && !is_chromecast && !is_fuchsia```](https://source.chromium.org/chromium/chromium/src/+/main:net/features.gni;l=20)

When creating the next Auth token, Cronet on Android refers to the [Android AccountManager](https://developer.android.com/reference/android/accounts/AccountManager) ([implementation](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/accounts/AccountManager.java)), which apparently takes care of dealing with the Kerberos library. The [HttpNegotiateAuthenticator](https://source.chromium.org/chromium/chromium/src/+/main:net/android/java/src/org/chromium/net/HttpNegotiateAuthenticator.java) is the Cronet Java wrapper allowing JNI interfacing.

On the C++ layer, Cronet invokes a [Java method](https://source.chromium.org/chromium/chromium/src/+/main:net/android/http_auth_negotiate_android.cc;l=147) to initiate the token generation. Creating the next Auth token is a blocking operation, so when the Cronet C++ layer needs one, the response is set up through a callback which invokes a [JNI method](https://source.chromium.org/chromium/chromium/src/+/main:net/android/java/src/org/chromium/net/HttpNegotiateAuthenticator.java;l=386).

**Comment by DavidSchinazi** [comment]
@carloseltuerto do we have any reason to believe that someone is using this feature?

**Comment by carloseltuerto** [comment]
@DavidSchinazi Unfortunately, I am not is a position to answer that question - I would not know what to look for. Maybe ex Cronet SWEs would know better?

**Comment by carloseltuerto** [comment]
According to SWEs with long involvement with Cronet (Misha Efimov, Paul Jensen), this is more likely a Chrome/Webview feature that may inadvertently work with Cronet. It is probably fine to implement only if someone complains loudly enough.

Closing.
