### ISSUE TITLE
Cronvoy: Use Java libraries for SSL related crypto

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1576]
For Android, in order to establish and maintain an SSL connection, the involved crypto operations are being performed by the [java.security.Signature](https://developer.android.com/reference/java/security/Signature) and the [javax/crypto/Cipher](https://developer.android.com/reference/javax/crypto/Cipher) classes.

For Android conformity, and to avoid any crypto surprises, using the same libraries seems desirable.

As usual, Cronet maintains a Java wrapper class allowing JNI interactions: [AndroidKeyStore](https://source.chromium.org/chromium/chromium/src/+/main:net/android/java/src/org/chromium/net/AndroidKeyStore.java). And this is the C++ code invoking the AndroidKeyStore class: [keystore.cc](https://source.chromium.org/chromium/chromium/src/+/main:net/android/keystore.cc)

**Comment by DavidSchinazi** [comment]
I don't think this is necessarily desirable, the BoringSSL cryptographic operations APIs are generally better maintained. @carloseltuerto can you post a link of where Cronet uses this today please? The key store you linked is about storing keys, not performing cryptographic operations.

**Comment by carloseltuerto** [comment]
This is at the heart of the Chromium Networking library - used for socket encryption and signing. Example:

https://source.chromium.org/chromium/chromium/src/+/main:net/ssl/ssl_platform_key_android.cc;l=124
https://source.chromium.org/chromium/chromium/src/+/main:net/socket/ssl_client_socket_impl.cc;l=1768

My guess is that it would potentially bring incompatibilities. Maybe that's a way to reduce code footprint. Maybe given all the different Android releases, they could be the safest path. Unfortunately, I personally can not tell if any of this is relevant - probably better to refer to a SWE with deep Android Encryption knowledge.

**Comment by DavidSchinazi** [comment]
Thanks for the links. This is about signatures, not encryption. It looks like Chrome uses this code to tell BoringSSL to use Android platform APIs for signatures for TLS client certificates. I don't think any users of Cronet use TLS client certificates, does Cronet have an API for those?

**Comment by carloseltuerto** [comment]
The Android ```keystore.cc``` under Chromium also has a method named [```EncryptWithPrivateKey```](https://source.chromium.org/chromium/chromium/src/+/main:net/android/keystore.cc;l=87)

The ```EncryptWithPrivateKey``` method is invoked by ```net/ssl/ssl_platform_key_android.cc```, method  [```SignPSSFallback```](https://source.chromium.org/chromium/chromium/src/+/main:net/ssl/ssl_platform_key_android.cc;l=168)

The ```SignPSSFallback``` method is invoked by ```net/ssl/ssl_platform_key_android.cc```, method  [```Sign```](https://source.chromium.org/chromium/chromium/src/+/main:net/ssl/ssl_platform_key_android.cc;l=116)

After some more indirections, the ```Sign``` method is invoked by ```net/socket/ssl_client_socket_impl.cc```, method [```SSLClientSocketImpl::PrivateKeySignCallback```](https://source.chromium.org/chromium/chromium/src/+/main:net/socket/ssl_client_socket_impl.cc;l=1768)

So this is part of the main SSL socket related logic. However, the encryption seems to be invoked as part of a fallback mechanism only. How much this is used today is not something I can determine. The ```ssl_client_socket_impl.cc``` is used by [Cronet](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=35) (obviously its Android flavor)

**Comment by carloseltuerto** [comment]
What is I guess disconcerting is that the supporting code is "Android" specific: https://source.chromium.org/chromium/chromium/src/+/main:net/android/keystore.cc
Maybe there has been a desire to support TLS client certificates, and this is in reality dead code.

**Comment by carloseltuerto** [comment]
According to Misha Efimov, this feature was probably designed for Android Chrome and Android Webview, but the Cronet API does not expose this feature. Might be needed in future, some potential use cases are related to Browser Apps, Banking Apps, and VPN apps.

Closing this.
