### ISSUE TITLE
Cronvoy: support stale DNS

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1587]
Cronet supports stale DNS: [stale_host_resolver.cc](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/stale_host_resolver.cc)

This feature can be configured with following arguments:

- [```delay_ms```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=106-108?q=delay_ms)
- [```max_expired_time_ms```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=109-111?q=max_expired_time_ms)
- [```allow_other_network```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=115-117?q=allow_other_network)
- [```persist_to_disk```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=118-119?q=persist_to_disk)
- [```persist_delay_ms```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=120-123?q=persist_delay_ms)
- [```use_stale_on_name_not_resolved```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=124-127?q=use_stale_on_name_not_resolved)

This feature was appreciated by YouTube: Total network error -4%

**Comment by alyssawilk** [comment]
also persist_to_disk as an option :-)

**Comment by alyssawilk** [comment]
I think we're roughly feature comparable apart from persist to disk which has its own tracking issue
