### ISSUE TITLE
Cronvoy: support for Async DNS

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1596]
Cronet supports two mechanism to resolve DNS:

- [Platform DNS Resolver](https://source.android.com/devices/architecture/modular-system/dns-resolver): by default
- The Chromium Async DNS Resolver: activated with an experimental feature flag: [```AsyncDNS```](https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/url_request_context_config.cc;l=97-98)

This may require changes in Envoy, but some questions must be answered first:
 - Is Envoy Mobile already doing something similar to the Chromium Async DNS Resolver?
 - Should the Platform DNS Resolver be used by default like it is today with Cronet?

Many Google Apps are setting that flag: Youtube, Google Search, Hangout, PlayStore. And an internal study seems to demonstrate the value of the Chromium Async DNS Resolver:
- Overall: improves Android DNS.TotalTime 16% (496 ms to 414 ms) at the 95th percentile.	
- Brazil:  improves Android DNS.TotalTime 35% (1875 ms to 1220 ms) at the 95th percentile

**Comment by RyanTheOptimist** [comment]
I'm not sure we need to support this per. se. Chrome/Cronet's AsyncDNS is really a performance optimization rather than feature. So I think we need to make sure that Envoy / Envoy Mobile has an outstanding DNS resolution subsystem and that should tick the box. What do you think?

**Comment by carloseltuerto** [comment]
Maybe the real question is should Cronvoy defaults to the Platform DNS Resolver, and therefore bypass the "Envoy Mobile potentially outstanding DNS resolution subsystem". As far as I can tell, this would mimic what happens with Cronet today.

**Comment by RyanTheOptimist** [comment]
I think Envoy currently uses the c-ares  resolver library to do resolutions (at least on non-apple platforms). I suspect that once we get to the point of benchmarking Cronvoy performance, we'll end up looking at the performance relative to Cronet.

**Comment by DavidSchinazi** [comment]
"Async DNS" was the name of a Chrome feature, it's not applicable outside of Chrome. Unless we have reason to believe that Envoy's DNS is inefficient, we don't need to do anything. If we do find inefficiencies, we'll resolve them, but we won't need to honor Cronet's "Async DNS" experimental option.

**Comment by carloseltuerto** [comment]
The title of this issue is now confusing.

Today Cronet uses by default the [Platform DNS Resolver](https://source.android.com/devices/architecture/modular-system/dns-resolver). They never updated to use the chromium//net AyncDNS - only our biggest apps use this override.

The real question is do we want to, by default, keep using the Platform DNS Resolver?

To be honest, I don't know why the chromium//net AyncDNS was never set as the default.

**Comment by DavidSchinazi** [comment]
I'd say by default we should just do what Envoy Mobile does. We can change that if we find a good reason to.

**Comment by carloseltuerto** [comment]
Let's close this for the moment.
