### ISSUE TITLE
Maven pom has wrong version

### ISSUE THREAD

**Issue by yschimke** [envoyproxy/envoy-mobile#1651]
https://repo1.maven.org/maven2/io/envoyproxy/envoymobile/envoy/0.4.0.04282021/envoy-0.4.0.04282021.pom

```
<version>main-259e825</version>
```

```
      > Could not resolve io.envoyproxy.envoymobile:envoy:0.4.0.04282021.
         > inconsistent module metadata found. Descriptor: io.envoyproxy.envoymobile:envoy:main-259e825 Errors: bad version: expected='0.4.0.04282021' found='main-259e825'
```

**Comment by buildbreaker** [comment]
@yschimke Thanks for surfacing this! I can take a look into fixing this in the next week

**Comment by buildbreaker** [comment]
Here's the offending line: https://github.com/envoyproxy/envoy-mobile/blob/main/.github/workflows/artifacts.yml#L30

**Comment by yschimke** [comment]
Will this make maven central? Seems like there are other build issues affecting publishing.
