### ISSUE TITLE
logging: create compilation switch to disable all logging

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#174]
Right now envoy compiles in all logging code by default. It does this regardless of logging level. Previously Envoy had a [`NVLOG`](https://github.com/envoyproxy/envoy/pull/2886) flag that allowed the user to compile out logging code. 

We should reintroduce this capability in order to remove all logging on release library versions of Envoy Mobile.

### Size Win

In my original, hacky, approach I removed all logging coarsely and got a ~500k size reduction in the binary size.

### Approach

Envoy has all logging macros defined in the https://github.com/envoyproxy/envoy/blob/master/source/common/common/logger.h header file. An approach to remove the logging code is to use ifdefs in the base `ENVOY_LOG_COMP_AND_LOG` macro. The wrinkle in this plan is that eliminating code at this level might leave several "unused" variables, and several expressions evaluated but not used. Any solution this low in the codebase will need to address these issues.

Another solution is to guard the callsites with the ifdef as NVLOG used to do.

**Comment by goaway** [comment]
It would also be nice to be able to compile out logging by level.

**Comment by jpsim** [comment]
I'm not following why we're disabling logging in EM in the first place? Logging is useful and we use logging in production at Lyft.

I can see how some users may not care about logging and would want the code size reduction, but I don't think that should be the default?

**Comment by alyssawilk** [comment]
I mean y'all suggested it :-P
I'm happy to not have it on by default, and for sure we'd want it on when debugging things but OOC how do you folks get stderr logs from users such that they're useful?

**Comment by jpsim** [comment]
> I mean y'all suggested it :-P

It's possible that we only started collecting logs after this issue was filed in 2019.

It's also possible that log collection via the log handler in the engine builder still works, even if logs aren't being sent to stderr. I'll have to do some testing.

**Comment by alyssawilk** [comment]
Nope - it basically removes the log macro so you won't want this on :-)

**Comment by jpsim** [comment]
I think we should also keep it on by default then.

**Comment by alyssawilk** [comment]
SG, I'll close this one out and we can disable it in our internal release builds (or at least quantify the memory and opt into having it when we want it)

**Comment by alyssawilk** [comment]
hm, actually one final question
does currently builder config allow for remote logsinks?  If only Lyft can take advantage of logs without additional work, maybe we should default them off in OSS release build just because it does help size and (currently) no one else can functionally use them

**Comment by jpsim** [comment]
Yes, it's possible for _any_ consumer of Envoy Mobile to define a log handler callback: https://github.com/envoyproxy/envoy-mobile/blob/6eafceba59ebe04f9e312ff6065d287a4eafab31/library/swift/EngineBuilder.swift#L419-L428
