### ISSUE TITLE
linking: alwayslink

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#175]
@kastiglione brought up an excellent point in https://github.com/lyft/envoy-mobile/issues/17#issuecomment-505151582 mentioning that the `envoy_cc_library` rules have an `alwayslink = 1` option set. This forces the linker to link all compilation units regardless of use, even when `-dead_strip` is passed to the linker.

We should make this optional, and make sure that linking is pessimistic enough that we don't run into runtime issues due to missing symbols when `-dead_strip` is involved.

### Size Win

@kastiglione reported a ~2mb reduction. Even as a ceiling this is a very attractive comparison, and thus we should investigate this with high priority.

**Comment by kastiglione** [comment]
I need to correct my statement, at least for iOS. I said `alwayslink` blocks `-dead_strip` which is technically **not** true. It's possible (in theory) for `-dead_strip` to undo the bloat inflicted by `alwayslink` (aka `-force_load`), but in practice that's not the case.

By default, `ld64` lazily loads from archives only the object files (compilation units) it the needs to resolve symbols. But, using `-force_load` means all object files from that archive are eagerly loaded and included in the final binary, regardless of references.

This all happens before `-dead_strip`. The result of doing this can change the symbol graph in some ways that `-dead_strip` can't undo. But it doesn't block `-dead_strip` entirely. In fact, in my test build, `-dead_strip` saves 6mb. Thankfully it's an easy fix.
