### ISSUE TITLE
upstream: remove json code

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#177]
Envoy has a significant amount of JSON code used for the V1 APIs. In several places this proves to be significant enough that we could investigate ways to compile it out ahead of the imminent V1 removal in envoy upstream.

### Size Win

Size wins could be seen across a variety of places. 

-  json loader code:

```
  17.8%  1.49Mi  17.8%  1.51Mi envoy common/
       5.0%  76.7Ki   5.0%  77.9Ki external/envoy/source/common/json/json_loader.cc
```

- strings from json schemas

- code from conversion code.

**Comment by mattklein123** [comment]
IMO it's not worth it to worry about this in the timeframe in which we are going to go fully to production. This should all be gone by then. cc @derekargueta

**Comment by alyssawilk** [comment]
v2 is gone and I don't see that file in bloaty so closing off.
