### ISSUE TITLE
linking: use dead_strip

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#180]
currently `dead_strip` is not used in the sizeopt config option. This is related to #175. Once #175 is closed, we can start using dead_strip. This should be documented in the binary size performance docs.

**Comment by keith** [comment]
FWIW dead strip won't apply when producing a static binary for iOS since that happens at link time

**Comment by alyssawilk** [comment]
@keith we good to close this one?

**Comment by keith** [comment]
yea, we should get this "for free" if it ever applies
