### ISSUE TITLE
MacOS: can't get backtraces outside of Xcode

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#1827]
Currently Envoy and Envoy Mobile do not print local stacktraces on MacOS. This is a long standing issue in the Envoy community and has not been resolved. Historical context [here](https://envoyproxy.slack.com/archives/C7B8QL52R/p1600798625006600).

Interestingly stack traces do get produced in release iOS apps with Envoy Mobile, or even when a crash happens locally in MacOS for an app running in XCode.

**Comment by junr03** [comment]
cc @ggreenway @keith as people that have helped try to solve this in the past. I think @lizan might have looked at this in a previous life too?

**Comment by keith** [comment]
In the short term you can view the reports here in Console.app https://support.apple.com/guide/console/reports-cnsl664be99a/mac

But it looks like this is just a macOS bug triggered by the signal handling configuration in envoy, working on that here https://github.com/envoyproxy/envoy/pull/18251

**Comment by keith** [comment]
My PR is merged upstream, so next submodule update this should be fixed here

**Comment by junr03** [comment]
Confirmed fixed. Thanks @keith
