### ISSUE TITLE
git: Write an envoy-mobile specific prepush bootstrap script

### ISSUE THREAD

**Issue by buildbreaker** [envoyproxy/envoy-mobile#185]
We should create our own bootstrap script rather than use envoy's

The contribution docs specify to use [`./envoy/support/bootstrap`](https://github.com/lyft/envoy-mobile/blob/50a452bd2c170b4c76f13f15a47b9190bad2d5d5/CONTRIBUTING.md#submitting-a-pr)

This will cause the envoy pre-push scripts (which use the formatting rules defined in envoy) instead of format file we have defined: https://github.com/lyft/envoy-mobile/blob/79dc7346047aa9c3b78d89af2d850ef75a97c0c1/tools/check_format.sh

This causes issues for pushing code because envoy's rules make assumptions that are not valid within envoy-mobile (adding `NOLINT` to java files, superfluous declaration of `@envoy`, etc).

**Comment by jpsim** [comment]
No longer relevant after the repo merge.
