### ISSUE TITLE
ci: use bazel cache

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#19]
Enable use of a bazel cache

**Comment by keith** [comment]
What's the blocker here now? Also note I'm working with Google to try remote execution with this project

**Comment by junr03** [comment]
No blocker @keith. We were waiting to get the project moved to this repo, open sourced, and ready with CI. Now that that is all done this issue is open to be worked on. If you want to take it on that would be awesome!

**Comment by jpsim** [comment]
CI uses bazel cache and remote exec thanks to EngFlow.
