### ISSUE TITLE
Support concurrent EM Engine

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#2003]
Today, due to some EnvoyProxy limitations, Envoy-Mobile can not run more than one Engine at a given moment. For the YouTube App, only one Engine is not viable - it needs at least two concurrent Engines.

TODO: upstream tests with tear down of A first, tear down of B first, different logging paths.

**Comment by alyssawilk** [comment]
Ok @goaway @junr03 the upstream part is "done enough" insofar as if you bump main it should work (and if not, it definitely works with envoy.restart_features.no_runtime_singleton = true, as that's what is regression tested)

**Comment by junr03** [comment]
I am going to close this issue (which is actually a duplicate of #332). I forgot that original one existed. Now that all the Envoy pieces are in, the more relevant context is @goaway's description in #332. Thanks for all the work @alyssawilk, as discussed in the community meeting on thursday, the team at Lyft will prioritize resources to work on this.
