### ISSUE TITLE
[CI] Run integration tests on EngFlow

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy-mobile#2020]
In https://github.com/envoyproxy/envoy-mobile/pull/1995 I disabled remote execution for the integration test CI jobs because of test failures that were only occurring when using remote execution but ran fine on GitHub Actions workers directly.

Here's the kind of failure we were seeing when running these tests with remote execution: https://github.com/envoyproxy/envoy-mobile/runs/4739746396?check_suite_focus=true

And the same tests running successfully without remote execution: https://github.com/envoyproxy/envoy-mobile/runs/4740616118?check_suite_focus=true

**Comment by lfpino** [comment]
We have an easy fix for this one. @WillEngFlow will send you a PR in a bit.

**Comment by jpsim** [comment]
The tests in `test/common/integration/BUILD` were re-enabled on EngFlow in #2022, but the tests in `test/swift/integration/BUILD` still have `no-remote-exec` so I'm reopening this ticket to track that.

**Comment by lfpino** [comment]
This will be fixed with https://github.com/envoyproxy/envoy-mobile/pull/2071
