### ISSUE TITLE
Flaky CI java tests

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#2073]
to: @lfpino

Envoy Mobile CI often fails with the flaky error:

```
ERROR: /Users/runner/work/envoy-mobile/envoy-mobile/test/java/org/chromium/net/urlconnection/BUILD:8:26: Testing //test/java/org/chromium/net/urlconnection:urlconnection_test failed: (Exit 34): NOT_FOUND: /var/lib/engflow/worker/cas/upload/877c9ebc-6c2b-4241-8179-52034ebe03cb (No such file or directory)
```

Retrying CI couple of time solves the issue.

Thanks! 

Charles.

**Comment by lfpino** [comment]
Looking now, @carloseltuerto do you know if it's only happening with specific tests? That'd help me narrow down the problem.

**Comment by lfpino** [comment]
According to our discussion, this wasn't reproducible https://envoyproxy.slack.com/archives/CKQ2LK23G/p1645782488294569?thread_ts=1645613021.362669&cid=CKQ2LK23G
