### ISSUE TITLE
android CI flake

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy-mobile#2343]
https://github.com/envoyproxy/envoy-mobile/runs/6781918882?check_suite_focus=true

In file included from external/com_google_absl/absl/hash/internal/city.cc:22:
In file included from external/com_google_absl/absl/hash/internal/city.h:48:
In file included from external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/stdint.h:106:
external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__config:218:12: fatal error: 'features.h' file not found
#  include <features.h>

passed happily on refresh

**Comment by jpsim** [comment]
This looks relevant: https://github.com/actions/virtual-environments/issues/5595
