### ISSUE TITLE
v0.5.0 failed sonatype/maven upload

### ISSUE THREAD

**Issue by buildbreaker** [envoyproxy/envoy-mobile#2555]
Hello,

Your maven upload failed on the latest release: https://github.com/envoyproxy/envoy-mobile/actions/runs/2981195191/jobs/4779197721

Error is thrown here: https://github.com/envoyproxy/envoy-mobile/blob/main/ci/sonatype_nexus_upload.py#L315

(It's a secret: https://github.com/envoyproxy/envoy-mobile/blob/main/.github/workflows/release.yml#L93)

**Comment by jpsim** [comment]
More recent deploys worked: https://repo1.maven.org/maven2/io/envoyproxy/envoymobile/envoy/
