### ISSUE TITLE
remove cares DNS dependency

### ISSUE THREAD

**Issue by Augustyniak** [envoyproxy/envoy-mobile#2629]
Discussed in [here](https://github.com/envoyproxy/envoy-mobile/pull/2618#discussion_r1000831843).

**Comment by jpsim** [comment]
I have a work in progress solution for this.

**Comment by jpsim** [comment]
https://github.com/envoyproxy/envoy/compare/main...jpsim:envoy:jp-disable-cares

**Comment by alyssawilk** [comment]
ok we still have the proto lingering but cares dep is gone with our default .bazelrc (skipping google gRPC which also pulls it in)
