### ISSUE TITLE
[CI] Update to Xcode 14.1

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy-mobile#2664]
This is now the latest stable Xcode release and we should update to it in order to compile against the latest iOS SDK.

* Version: 14.1 (14A309)
* Release Notes: https://developer.apple.com/documentation/xcode-release-notes/xcode-14_1-release-notes
* Download: https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_14.1/Xcode_14.1.xip

Will require EngFlow to update their executors just as was done for #2544. A macOS version update should not be necessary.

cc @lfpino @Yannic

**Comment by lfpino** [comment]
Ack @jpsim I'll create an internal request to get this done asap

**Comment by lfpino** [comment]
HI @jpsim, we've scheduled time on Monday to prepare the install in the cluster, we'll keep you posted.

cc @drwx

**Comment by drwx** [comment]
We have the changes (xcode 14.1 snapshots) ready to be rolled out.

**Comment by jpsim** [comment]
Thanks for the quick turnaround @lfpino and @drwx!

How can we test on that new snapshot? Can we point a PR to a temporary cluster to validate?

I'll put up a PR with the non-EngFlow changes that we can use to validate.

**Comment by jpsim** [comment]
If we can point https://github.com/envoyproxy/envoy-mobile/pull/2674 to a staging cluster with Xcode 14.1 installed it should work.

**Comment by drwx** [comment]
Unfortunately, the rollout of mac instances needs some manual intervention on the AWS console. We will update here once all the mac instances are recycled.

**Comment by drwx** [comment]
@jpsim we have refreshed the mac instances (4 out of 5) and they should have Xcode 14.1.  AFAICT there's no staging/temp cluster for testing.
If you had mac workloads running, they should just continue to work, at least that's the hope.

**Comment by jpsim** [comment]
Thanks @drwx, #2674 is passing, can you please complete the rollout and we'll merge?
