### ISSUE TITLE
Enable Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [envoyproxy/envoy-mobile#2680]
As discussed elsewhere (https://cncfservicedesk.atlassian.net/browse/CNCFSD-1458), the plan is to enable GA4 by using the existing GA4 Envoy web data stream with ID `G-DXJEH1ZRXX`.

For some context, the main repo was migrated to GA4 via:

- https://github.com/envoyproxy/envoy-website/issues/273

Let's use this issue to discuss implementation details.

Tasks:

- [x] Add GA4 ID to main site pages (that is, non-doc pages)
    https://github.com/envoy-mobile/envoy-mobile.github.io/pull/27
- [x] #2681

**Comment by chalin** [comment]
From @jpsim:

> The Envoy Mobile website is hosted by GitHub Pages here: [GitHub - envoy-mobile/envoy-mobile.github.io: Envoy Proxy website](https://github.com/envoy-mobile/envoy-mobile.github.io) 
> 
> The site is auto-generated using Sphinx whenever there are changes to the Envoy Mobile repo: [envoy-mobile/docs at main · envoyproxy/envoy-mobile](https://github.com/envoyproxy/envoy-mobile/tree/main/docs) 
> 
> I was able to hook up Google Analytics in Sphinx using this extension: [GitHub - sphinx-contrib/googleanalytics](https://github.com/sphinx-contrib/googleanalytics) 
> 
> However, it seems to expect a GA tag with the format `UA-123-123-123`, will that work with the `G-DXJEH1ZRXX` tag that you shared earlier?

I'm not familiar with that extension so I don't know if it supports GA4. We can give it a try :).

**Comment by jpsim** [comment]
Giving it a try here: https://github.com/envoyproxy/envoy-mobile/pull/2681

**Comment by chalin** [comment]
I'm not seeing any GA4 ID in the site pages, are you @jpsim? If not, can you re-open this issue :)?

**Comment by chalin** [comment]
Oh ... now that I've caught up with your comment in the Jira ticket, I see that what you've done is enabled GA over the doc pages. I was looking at the main site. Can you reopen this issue so that we can use it to track the addition of GA to the main site too?

**Comment by jpsim** [comment]
Since you have access to the analytics dashboard, can you check if you see traffic from the EM docs site which was deployed about an hour ago? Like on this page? https://envoymobile.io/docs/envoy-mobile/latest/index.html

**Comment by chalin** [comment]
AFAIK, the GA4 console doesn't, at the moment, have as good realtime traffic data as UA does, so I can't tell if there's traffic from the EM docs site yet. Usually, I test pages in true realtime using the Google Tag Assistant, but it is refusing to connect to the site, apparently because the homepage doesn't have a GA ID.

@jpsim - can you add the GA4 ID to all of the main (non-docs) site pages? Then I'll be able to use the tag assistant.

**Comment by jpsim** [comment]
Ok @chalin, I just updated the only other non-doc page in https://github.com/envoy-mobile/envoy-mobile.github.io/pull/27

**Comment by jpsim** [comment]
Seems to be hooked up correctly on the website side of things. Here's the network activity when loading https://envoymobile.io before and after https://github.com/envoy-mobile/envoy-mobile.github.io/pull/27:

## Before

![before](https://user-images.githubusercontent.com/474794/202340659-fe5b6030-3c31-4bcd-9e9b-2922ec31cdd8.png)

## After

![after](https://user-images.githubusercontent.com/474794/202340603-8e4401ff-18e0-4152-b7f3-5dc5476665e5.png)

**Comment by chalin** [comment]
From the analytics console I'm seeing traffic only from the landing page:

> <img width="1436" alt="image" src="https://user-images.githubusercontent.com/4140793/202588431-90750f7f-2577-4a20-b511-2960331b34a8.png">

Your "after" network screenshot above confirms that the `sphinxcontrib.googleanalytics ` plugin uses the old `analytics.js` library. GA4 requires the `gtag.js` library. Maybe you can propose an update to the plugin? (For details see, [Migrate from analytics.js to gtag.js (Universal Analytics)](https://developers.google.com/analytics/devguides/migration/ua/analyticsjs-to-gtagjs).)

**Comment by chalin** [comment]
I see that the `sphinxcontrib.googleanalytics ` plugin was updated to support `gtag.js` in August: https://github.com/sphinx-contrib/googleanalytics/blob/42b3df99fdc01a136b9c575f3f251ae80cdfbe1d/sphinxcontrib/googleanalytics.py#L13

So maybe it's a question of fetching the latest version?

**Comment by chalin** [comment]
Here is what I used on another project:

```text
sphinxcontrib-googleanalytics @ git+https://github.com/sphinx-contrib/googleanalytics.git@42b3df99fdc01a136b9c575f3f251ae80cdfbe1d
```

**Comment by jpsim** [comment]
We require tagged releases for our Python dependencies. Here's what I get when I point to the latest commit:

```
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    sphinxcontrib-googleanalytics@ git+https://github.com/sphinx-contrib/googleanalytics.git@42b3df99fdc01a136b9c575f3f251ae80cdfbe1d from git+https://github.com/sphinx-contrib/googleanalytics.git@42b3df99fdc01a136b9c575f3f251ae80cdfbe1d (from -r ./docs/requirements.txt (line 105))
```

I've requested a tagged release in https://github.com/sphinx-contrib/googleanalytics/issues/5

**Comment by jpsim** [comment]
Updating in https://github.com/envoyproxy/envoy-mobile/pull/2708
