### ISSUE TITLE
remove downstream listeners from Envoy Mobile build

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy-mobile#2711]
based on a hacked up prototype looks like ~1M savings

**Comment by alyssawilk** [comment]
@jpsim next step is y'all experimenting with the use_api_listener runtime guard.

**Comment by jpsim** [comment]
That'd be `setRuntimeGuard("use_api_listener", true / false)` right? Is there a way we can observe if it's being applied correctly?

**Comment by jpsim** [comment]
I'm comfortable removing the listeners completely. It looks like all our unit and integration tests pass with listeners disabled and I don't think we need to run a production experiment for this.
