### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by fortuna** [envoyproxy/envoy-mobile#2724]
It seems there hasn't been any activity and releases since 2022. Has the project been abandoned? Did it move somewhere else? What happened?

I'm trying to decide whether to use it, but I'll likely avoid it if it's no longer maintained.

Thank you.

**Comment by fredyw** [comment]
It's not abandoned. The project has been moved to https://github.com/envoyproxy/envoy/tree/main/mobile

**Comment by fortuna** [comment]
Excellent. thank you!

**Comment by fortuna** [comment]
@fredyw BTW, the website is pointing to https://github.com/envoyproxy/envoy-mobile, which is misleading.

**Comment by fredyw** [comment]
Yup, I just noticed that, too and created https://github.com/envoyproxy/envoy/issues/36127 to fix it.
