### ISSUE TITLE
test: run oss Envoy tests against mobile targets

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#6]
Currently Envoy OSS's test suite does not run against mobile architectures. We would like to enable the full (or as close as reasonably possible) test suite to run against mobile architectures. This will enable envoy-mobile's CI to run tests against upstream.

Changes need to happen on two broad categories for this to be possible:
1. Build changes: we need to create bazel infrastructure to selectively depend, compile, and run code against mobile architectures. Inspiration can be take from [`envoy_cc_platform_dep`](https://github.com/envoyproxy/envoy/blob/b81ff993d954c2539d0c60d736d1322f13682dfe/bazel/envoy_build_system.bzl#L267) which allows to select dependencies against different build targets.
2. Code changes: there are a few refactors, and code additions that need to happen in order to be able to run tests against mobile architecture targets:
   -  filesystem: we need to use iOS and Android filesystem constructs were appropriate. Thankfully, folks from the OSS community made the barrier to entry of this work more manageable when introducing win32 filesystem implementations.
   -  via @keith `the google test stuff has some "expect death" stuff that needs to be solved somehow since on iOS you only ever have 1 process. totally unclear to me, even from the feature side, how we would want that to work` his opinion is that this could be deferred.

cc @keith who was previously working on this.

**Comment by junr03** [comment]
recent dependency updates in Envoy have caused breakages in Envoy Mobile. This is another reason to run envoy mobile tests in Envoy CI.

**Comment by moderation** [comment]
Another required revert on Envoy main for a mobile issue - https://github.com/envoyproxy/envoy/pull/18566

**Comment by keith** [comment]
One option outside of setting up a dependency between envoy -> envoy-mobile would just be to build whatever targets are a good indication of compatibility against the iOS / Android SDKs on envoy's normal CI. This wouldn't require significantly more build setup overhead, but would at least shed light on most build issues.

**Comment by jpsim** [comment]
Now that Envoy Mobile has been moved to the Envoy repo, we build and test parts of Envoy Mobile for every Envoy PR.

Depending on CI capacity, it'd be good to also build and run one iOS target and one Android target.

For the most part, this should reduce the number of Envoy changes that break Envoy Mobile and I'll be closing this ticket.
