### ISSUE TITLE
dispatcher: implement readDisable()

### ISSUE THREAD

**Issue by rebello95** [envoyproxy/envoy-mobile#825]
(Follow up to https://github.com/lyft/envoy-mobile/pull/824).

By adding `NOT_IMPLEMENTED_GCOVR_EXCL_LINE` to `DirectStream::readDisable()`, we noticed that this function is actually being called in production (typically when using Envoy Mobile to upload files), and was thus leading to crashes from the assertion.

We should implement this function as necessary (the interface for which is defined [here](https://github.com/envoyproxy/envoy/blob/b6c8bb3a4ac6bcce221643a4924befd5eefd6815/include/envoy/network/connection.h#L142-L154) with docs).

Examples of use upstream:
- API listener no-ops ([link](https://github.com/envoyproxy/envoy/blob/b6c8bb3a4ac6bcce221643a4924befd5eefd6815/source/server/api_listener_impl.h#L103))
- Connection impl does quite a bit of state tracking ([link](https://github.com/envoyproxy/envoy/blob/b6c8bb3a4ac6bcce221643a4924befd5eefd6815/source/common/network/connection_impl.cc#L309-L368))
- QUIC also does similar state tracking ([link](https://github.com/envoyproxy/envoy/blob/b6c8bb3a4ac6bcce221643a4924befd5eefd6815/source/extensions/quic_listeners/quiche/envoy_quic_stream.h#L31-L71))

**Comment by alyssawilk** [comment]
Done in https://github.com/envoyproxy/envoy-mobile/pull/1545
