### ISSUE TITLE
Add docker image for kotlin linting to dockerhub

### ISSUE THREAD

**Issue by buildbreaker** [envoyproxy/envoy-mobile#97]
Context: https://github.com/lyft/envoy-mobile/pull/96#discussion_r294037011

Currently, we're using scripts to install [`detekt`](https://github.com/arturbosch/detekt). The reason we went with an interim solution is because we wanted to get something on CI integrated first.

We would like to move this to a docker image and upload it to docker hub. This will allow us to improve the linting and format checks in the future

**Comment by jpsim** [comment]
https://github.com/envoyproxy/envoy-mobile/pull/810
